name: Android CI

on:
  push:
    branches:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Store apk artifacts
      uses: actions/upload-artifact@v2
      with:
        name: apk-files-${{ github.sha }}
      # android stores build files in app/build - currently in .gitignore so it's not stored from local machine build & tests
        path: app/build/outputs/apk/release/

  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Pull artifacts
      uses: actions/download-artifact@v2
      with:
        name: apk-files-${{ github.sha }}

    - name: test for artifacts
      run: ls -lah